name: Update Submodule Staging

on:
  repository_dispatch:
    types: [submodule-updated-staging]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Submodule Staging
        run: |
          git fetch origin staging
          git checkout staging

          # Update the submodule
          git submodule update --remote --merge

          # Commit and push the updated submodule reference
          git add USupport-components-library
          git commit -m "Update USupport-components-library to latest staging"
          git push origin staging
